workflows:
  ios-native-pro-release:
    name: iOS Native PRO Release
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        provisioning_profiles:
          - CruxParansPro_Profile
        certificates:
          - CruxParans_Dist
      vars:
        BUILD_TYPE: "TEST"
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen
      - name: Generate Xcode Project
        script: |
          xcodegen generate
      - name: Set up signing certificate
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build Pro Edition
        script: |
          xcode-project build-ipa --project "CruxParans.xcodeproj" --scheme "CruxParansPro"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  ios-native-btoc-release:
    name: iOS Native BtoC (Free) Release
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        provisioning_profiles:
          - CruxParans_Profile
        certificates:
          - CruxParans_Dist
      vars:
        BUILD_TYPE: "TEST"
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen
      - name: Generate Xcode Project
        script: |
          xcodegen generate
      - name: Set up signing certificate
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Dry Run Compile (Check for Swift Errors)
        script: |
          xcodebuild clean build -project "CruxParans.xcodeproj" -scheme "CruxParans" -destination "generic/platform=iOS" CODE_SIGNING_ALLOWED=NO
      - name: Build BtoC Edition
        script: |
          xcode-project build-ipa --project "CruxParans.xcodeproj" --scheme "CruxParans"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
