workflows:
  ios-native-release:
    name: iOS Native Release Build
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.alpheratzlab.cruxparanspro
      vars:
        BUILD_TYPE: "TEST"
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen
      - name: Generate Xcode Project
        script: |
          xcodegen generate
      - name: Set up signing certificate
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build Pro Edition
        script: |
          xcode-project build-ipa --project "CruxParans.xcodeproj" --scheme "CruxParansPro"
    artifacts:
      - build/ios/ipa/*.ipa
